#include"../react.h"
#include <fstream>
#include <iostream>
using namespace std;

int main() {
    init();


    if (just_starting()) {
        add_yaml("home.yaml");
        print_at(0, "Up next:");
        print_at(10, "Software Design");
        print_at(30, "9 - 10");
        print_at(50, "Mon, Nov 18");
        print_at(70, "Software Design");
        print_at(90, "9 - 10");
        print_at(110, "Hardware Design");
        print_at(130, "10:45 - 11:40");
        print_at(150, "Psychology reading");
        print_at(170, "1 - 2:30");
        print_at(190, "Work");
        print_at(210, "3 - 6");
        
    }else if (received_event()) {
        if (event_id_is("person")) {
            add_yaml("personalization.yaml");
            print_at(0, "On");
            print_at(4, "Sun");
            print_at(8, "Mon");
            print_at(12, "Tue");
            print_at(16, "Wed");
            print_at(20, "Thu");
            print_at(24, "Fri");
            print_at(28, "Sat");
            print_at(32, "How long do you usually spend");
            print_at(70, "Sleeping");
            print_at(80, "HR");
            print_at(84, ":");
            print_at(86, "MN");
            print_at(90, "When");
            print_at(95, "HR");
            print_at(100, ":");
            print_at(102, "MN");
            print_at(106, "AM");
            print_at(110, "PM");
            print_at(115, "Breakfast");
            print_at(125, "HR");
            print_at(130, ":");
            print_at(132, "MN");
            print_at(136, "HR");
            print_at(140, ":");
            print_at(142, "MN");
            print_at(146, "AM");
            print_at(150, "PM");
            print_at(155, "Lunch");
            print_at(165, "HR");
            print_at(170, ":");
            print_at(172, "MN");
            print_at(176, "HR");
            print_at(180, ":");
            print_at(182, "MN");
            print_at(186, "AM");
            print_at(190, "PM");
            print_at(195, "Dinner");
            print_at(205, "HR");
            print_at(210, ":");
            print_at(212, "MN");
            print_at(216, "HR");
            print_at(220, ":");
            print_at(222, "MN");
            print_at(226, "AM");
            print_at(230, "PM");
            print_at(235, "Work");
            print_at(245, "HR");
            print_at(250, ":");
            print_at(252, "MN");
            print_at(256, "HR");
            print_at(260, ":");
            print_at(262, "MN");
            print_at(266, "AM");
            print_at(270, "PM");
            print_at(275, "Other");
            print_at(285, "HR");
            print_at(290, ":");
            print_at(292, "MN");
            print_at(296, "HR");
            print_at(300, ":");
            print_at(302, "MN");
            print_at(306, "AM");
            print_at(310, "PM");
            print_at(315, "Class Name");
            print_at(330, "Duration");
            print_at(340, "HR");
            print_at(345, ":");
            print_at(347, "MN");
            print_at(350, "When");
            print_at(355, "HR");
            print_at(360, ":");
            print_at(362, "MN");
            print_at(366, "AM");
            print_at(370, "PM");
            print_at(375, "Add a Class");
        }else if (event_id_is("event")) {
            add_yaml("addEvent.yaml");
            print_at(0,"Event type");
            print_at(15,"Event");
            print_at(25,"Homework");
            print_at(35,"Exam");
            print_at(50,"Event title");
            print_at(65,"Enter title:");
            print_at(80,"On");
            print_at(85,"MM");
            print_at(90,"DD");
            print_at(95,"YY");
            print_at(100,"From");
            print_at(105,"HR");
            print_at(108,":");
            print_at(110,"MN");
            print_at(115,"PM");
            print_at(120,"AM");
            print_at(125,"To");
            print_at(130,"HR");
            print_at(133,":");
            print_at(135,"MN");
            print_at(140,"PM");
            print_at(145,"AM");
            print_at(150, "Description");
            print_at(170, "Enter something here");
            print_at(270, "Create event");
        }else if (event_id_is("expanded")) {
            add_yaml("expandedOutput.yaml");
            print_at(0, "S");
            print_at(4, "M");
            print_at(8, "T");
            print_at(12, "W");
            print_at(16, "Th");
            print_at(20, "F");
            print_at(24, "S");
            print_at(30, "Today's Top 3:");
            print_at(50, "Exam");
            print_at(70, "Due: 11/18/19");
            print_at(90, "Work for 1 hour");
            print_at(110, "Homework");
            print_at(130, "Due: 11/22/19");
            print_at(150, "Work for 30 mins");
            print_at(170, "Paper");
            print_at(190, "Due: 11/25/19");
            print_at(210, "Work for 1 hour");
        }else if(event_id_is("home1")) {
            add_yaml("testHome.yaml");
            print_at(0, "Up next:");
            print_at(10, "Software Design");
            print_at(30, "9 - 10");
            print_at(50, "Mon, Nov 18");
            print_at(70, "Software Design");
            print_at(90, "9 - 10");
            print_at(110, "Hardware Design");
            print_at(130, "10:45 - 11:40");
            print_at(150, "Psychology reading");
            print_at(170, "1 - 2:30");
            print_at(190, "Work");
            print_at(210, "3 - 6");
            print_at(230, "SD Project");
            print_at(250, "7 - 9");
        }else if(event_id_is("home")) {
            add_yaml("home.yaml");
            print_at(0, "Up next:");
            print_at(10, "Software Design");
            print_at(30, "9 - 10");
            print_at(50, "Mon, Nov 18");
            print_at(70, "Software Design");
            print_at(90, "9 - 10");
            print_at(110, "Hardware Design");
            print_at(130, "10:45 - 11:40");
            print_at(150, "Psychology reading");
            print_at(170, "1 - 2:30");
            print_at(190, "Work");
            print_at(210, "3 - 6");
        }else if (event_id_is("expanded1")) {
            add_yaml("testExpandedOutput.yaml");
            print_at(0, "S");
            print_at(4, "M");
            print_at(8, "T");
            print_at(12, "W");
            print_at(16, "Th");
            print_at(20, "F");
            print_at(24, "S");
            print_at(30, "Today's Top 3:");
            print_at(50, "Exam");
            print_at(70, "Due: 11/18/19");
            print_at(90, "Work for 1 hour");
            print_at(110, "Homework");
            print_at(130, "Due: 11/22/19");
            print_at(150, "Work for 30 mins");
            print_at(170, "Paper");
            print_at(190, "Due: 11/25/19");
            print_at(210, "Work for 1 hour");
        }else if (event_id_is("priorities")) {
            print_at(0, "On");
            print_at(5, "Sun");
            print_at(10, "Mon");
            print_at(15, "Tues");
            print_at(20, "Wed");
            print_at(25, "Thurs");
            print_at(30, "Fri");
            print_at(35, "Sat");
            print_at(40, "Highest Priority");
            print_at(60, "SD Homework");
            print_at(80, "Math Exam");
            print_at(100, "Psychology Exam");
            print_at(120, "SD Project");
            print_at(140, "- -");
            print_at(145, "Lowest Priority");
            add_yaml("priorities.yaml");
        }
    }
    quit();
}